export const expenses = [
  {
    title: "Mandi",
    amount: 769,
    notes: "birthday treat",
    category: "food",
    time: "2:52",
    id: Date.now(),
  },
  {
    title: "Watch",
    amount: 3000,
    notes: "birthday gift",
    category: "Gift",
    time: "2:52",
    id: Date.now(),
  },
  {
    title: "Mandi",
    amount: 769,
    notes: "birthday treat",
    category: "food",
    time: "2:52",
    id: Date.now(),
  },
  {
    title: "Watch",
    amount: 3000,
    notes: "birthday gift",
    category: "Gift",
    time: "2:52",
    id: Date.now(),
  },
  {
    title: "Mandi",
    amount: 769,
    notes: "birthday treat",
    category: "food",
    time: "2:52",
    id: Date.now(),
  },
  {
    title: "Watch",
    amount: 3000,
    notes: "birthday gift",
    category: "Gift",
    time: "2:52",
    id: Date.now(),
  },
  {
    title: "Mandi",
    amount: 769,
    notes: "birthday treat",
    category: "food",
    time: "2:52",
    id: Date.now(),
  },
  {
    title: "Watch",
    amount: 3000,
    notes: "birthday gift",
    category: "Gift",
    time: "2:52",
    id: Date.now(),
  },
  {
    title: "Mandi",
    amount: 769,
    notes: "birthday treat",
    category: "food",
    time: "2:52",
    id: Date.now(),
  },
  {
    title: "Watch",
    amount: 3000,
    notes: "birthday gift",
    category: "Gift",
    time: "2:52",
    id: Date.now(),
  },
  {
    title: "Mandi",
    amount: 769,
    notes: "birthday treat",
    category: "food",
    time: "2:52",
    id: Date.now(),
  },
  {
    title: "Watch",
    amount: 3000,
    notes: "birthday gift",
    category: "Gift",
    time: "2:52",
    id: Date.now(),
  },
];
